= MOD-RS485-ISO =

This library is for control MOD-RS485-ISO module.
For more information on device please check site:
https://www.olimex.com/Products/Modules/Interface/MOD-RS485-ISO/open-source-hardware

Download the whole repository as an archive and load the library
in Arduino IDE from Sketch -> Inlcude Library -> Add .ZIP library...

Then the examples would be visible in File -> Examples (under the correct sub-group). 


== License ==

Copyright (c) 2017 Olimex Ltd.  All rights reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
